version = 1

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "bandit"
enabled = true

[[analyzers]]
name = "coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true
