name: Environment Validation

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - dev
      - qa
      - uat
      - stage
      - main

jobs:
  env-check:
    name: Validate Environment Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print GitHub Context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"

      - name: Print ENV_NAME Secret
        env:
          ENV_NAME: ${{ secrets.ENV_NAME }}
        run: |
          if [ -z "$ENV_NAME" ]; then
            echo "ERROR: ENV_NAME secret is missing!"
            exit 1
          fi
          echo "✅ ENV_NAME detected: $ENV_NAME"

      - name: Success Message
        run: echo "Workflow completed successfully for ${{ github.ref_name }}"
