name: Environment Validation

on:
  workflow_dispatch:
  push:
    branches: [dev, qa, uat, stage, main]

jobs:
  validate-dev:
    if: ${{ github.ref_name == 'dev' }}
    name: Validate DEV
    runs-on: ubuntu-latest
    environment: DEV                # ← ensures DEV’s secrets are available
    steps:
      - uses: actions/checkout@v3
      - name: Print context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: DEV"
      - name: Check ENV_NAME secret
        run: |
          if [ -z "${{ secrets.ENV_NAME }}" ]; then
            echo "ERROR: ENV_NAME secret missing in DEV environment"
            exit 1
          fi
          echo "ENV_NAME=${{ secrets.ENV_NAME }}"

  validate-qa:
    if: ${{ github.ref_name == 'qa' }}
    name: Validate QA
    runs-on: ubuntu-latest
    environment: QA                # ← QA environment
    steps:
      - uses: actions/checkout@v3
      - name: Print context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: QA"
      - name: Check ENV_NAME secret
        run: |
          if [ -z "${{ secrets.ENV_NAME }}" ]; then
            echo "ERROR: ENV_NAME secret missing in QA environment"
            exit 1
          fi
          echo "ENV_NAME=${{ secrets.ENV_NAME }}"

  validate-uat:
    if: ${{ github.ref_name == 'uat' }}
    name: Validate UAT
    runs-on: ubuntu-latest
    environment: UAT               # ← UAT environment
    steps:
      - uses: actions/checkout@v3
      - name: Print context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: UAT"
      - name: Check ENV_NAME secret
        run: |
          if [ -z "${{ secrets.ENV_NAME }}" ]; then
            echo "ERROR: ENV_NAME secret missing in UAT environment"
            exit 1
          fi
          echo "ENV_NAME=${{ secrets.ENV_NAME }}"

  validate-stage:
    if: ${{ github.ref_name == 'stage' }}
    name: Validate STAGE
    runs-on: ubuntu-latest
    environment: STAGE             # ← STAGE environment
    steps:
      - uses: actions/checkout@v3
      - name: Print context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: STAGE"
      - name: Check ENV_NAME secret
        run: |
          if [ -z "${{ secrets.ENV_NAME }}" ]; then
            echo "ERROR: ENV_NAME secret missing in STAGE environment"
            exit 1
          fi
          echo "ENV_NAME=${{ secrets.ENV_NAME }}"

  validate-prod:
    if: ${{ github.ref_name == 'main' }}
    name: Validate PROD
    runs-on: ubuntu-latest
    environment: PROD              # ← PROD environment
    steps:
      - uses: actions/checkout@v3
      - name: Print context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: PROD"
      - name: Check ENV_NAME secret
        run: |
          if [ -z "${{ secrets.ENV_NAME }}" ]; then
            echo "ERROR: ENV_NAME secret missing in PROD environment"
            exit 1
          fi
          echo "ENV_NAME=${{ secrets.ENV_NAME }}"
