name: Environment Validation

on:
  push:
    branches:
      - dev
      - qa
      - uat
      - stage
      - main

jobs:
  validate-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Validate Environment Setup
        env:
          ENV_NAME: ${{ secrets.ENV_NAME }}
        run: |
          if [ -z "$ENV_NAME" ]; then
            echo "ERROR: ENV_NAME secret is missing!"
            exit 1
          fi
          echo "ENV_NAME detected: $ENV_NAME"

      - name: Success Message
        run: echo "Workflow completed successfully for branch ${{ github.ref_name }}"
